# Generated by Django 2.2.4 on 2019-08-21 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=200)),
                ('team_2', models.CharField(max_length=200)),
                ('winner', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('week', models.IntegerField(default=0)),
                ('team_1_logo', models.URLField()),
                ('team_2_logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('team', models.CharField(max_length=200)),
                ('point_awarded', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
