# Generated by Django 2.2.4 on 2019-08-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflgame',
            name='team_1_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HomeTeamLogo', to='nfl.NFLTeam'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='team_2_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwayTeamLogo', to='nfl.NFLTeam'),
        ),
    ]
