# Generated by Django 2.2.4 on 2019-08-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0006_usermadepick'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermadepick',
            name='been_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpicks',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
