# Generated by Django 2.2.4 on 2019-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0007_auto_20190829_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermadepick',
            name='been_checked',
            field=models.BooleanField(),
        ),
    ]
