# Generated by Django 2.2.4 on 2019-09-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0008_auto_20190829_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflgame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WinningTeam', to='nfl.NFLTeam'),
        ),
    ]
