# Generated by Django 2.2.4 on 2019-09-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_auto_20190902_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermadepick',
            name='been_checked',
            field=models.BooleanField(),
        ),
    ]
